#' ---
#' title: Unified data-management in SHeS-pilot
#' subtitle: Additional information to be put in "controls"
#' author: jriou
#' date: 2024-06-06
#' ---

fn_000_additional_controls = function(cc) {
  
  # select what PFAS are considered in the analysis
  pfas_raw = 
    suppressMessages(readr::read_csv2(file.path(cc$data_path,"1.4.5_PFAS_v1.0_20230901.csv"),
                                      col_select = -1))
  # retrieve corresponding labels
  pfas_labels = 
    suppressMessages(readr::read_csv2(file.path(cc$data_path,"../FINAL DATA codebooks/1.4.5_PFAS_codebook_v2.0_20230901.csv"),
                                      col_select = 4)) %>% 
    dplyr::slice(-(1:2)) %>% 
    pull()
  pfas_list = names(pfas_raw)[-(1:2)]
  
  # variables labels
  labs = list(age="Age",
              gender="Sex",
              age_group="Age group",
              date="Inclusion date",
              age_group1830 ="Age group: 18 to 30",
              age_group3040 ="Age group: 31 to 40",
              age_group4050 ="Age group: 41 to 50",
              age_group5060 ="Age group: 51 to 60",
              age_group6070 ="Age group: 61 to 70",
              female0="Males",
              female="Females ",
              genderFemales='Females  ',
              genderMales='Males  ',
              a1_foreignForeignnationality='Foreign nationality ',
              
              a1_foreign0="Swiss nationality",
              a1_foreign="Foreign nationality",
              a1_education="Education ",
              a1_education_3classes="Education",
              a1_education_3classesUptohighschool = "Education: high school",
              a1_education_3classesApprenticeshipDprofessionalbaccalaureate = "Education: apprenticeship",
              a1_education_3classesUniversity ="Education: university",
              a1_university="University-level education",
              a1_household_monthly_income="Household monthly income ",
              a1_household_monthly_income_3classes="Household monthly income",
              `a1_household_monthly_income_3classesCHF4500`="Income: <CHF 4,500",
              `a1_household_monthly_income_3classesCHF4500to9000`="Income: CHF 4,500 to 9,000",
              `a1_household_monthly_income_3classes>CHF9000`="Income: >CHF 9,000",
              a1_income_lowest="Household monthly income <CHF 3,000",
              a1_income_highest="Household monthly income >CHF 11,000",
              
              center_label="Study site",
              center_labelBern="Bern",
              center_labelLausanne="Lausanne",
              pfas_not_done="PFAS missing",
              
              corona_vaccine_sarscov2="Anti-SARS-CoV-2 vaccination",
              corona_past_disease_confirmed="Past confirmed SARS-CoV-2 infection",
              corona_past_disease_suspected="Past confirmed or suspected SARS-CoV-2 infection",
              corona_past_disease_date="Date of past SARS-CoV-2 infection",
              
              bu_antiS_igg_nonzero="Anti-S IgG (detected)",
              bu_antiS_igg_quant="Anti-S IgG (quantitative)",
              bu_antiN_igg_nonzero="Anti-N IgG  (detected)",
              bu_antiN_igg_quant="Anti-N IgG (quantitative)",
              bu_ratio_iga_nonzero="Ratio Anti-SARS-CoV-2 IgA (detected)",
              bu_ratio_iga_quant="Ratio Anti-SARS-CoV-2 IgA (quantitative)",
              bu_ige_quant="Anti-SARS-CoV-2 IgE (quantitative)",
              
              corona_time_since_past_disease="Days since SARS-CoV-2 infection",
              corona_past_hospit="Hospitalization linked to SARS-CoV-2 infection",
              corona_past_icu="ICU stay linked to SARS-CoV-2 infection",
              corona_vaccine_sarscov2="SARS-CoV-2 vaccination",
              
              scre_smoker0="Non smoker",
              scre_smoker="Smoker",
              # scre_food_nuts0="No nuts in the last 24h",
              # scre_food_nuts="Nuts in the last 24h",
              # scre_food_fresh_fruit="No  fruits in the last 24h",
              # scre_food_fresh_fruit="Fruits in the last 24h",
              # scre_food_fresh_vegetables0="No vegetables in the last 24h",
              # scre_food_fresh_vegetables="Vegetables in the last 24h",
              # scre_food_fresh_spices0="No indian spices in the last 24h",
              # scre_food_fresh_spices="Indian spices in the last 24h",
              # scre_food_fresh_crude_oil0="No vegetable oil in the last 24h",
              # scre_food_fresh_crude_oil="Vegetable oil in the last 24h",
              # scre_food_fresh_processed0="No processed food in the last 24h",
              # scre_food_fresh_processed="Processed food in the last 24h",
              # scre_food_fresh_deep_fried0="No fried food in the last 24h",
              # scre_food_fresh_deep_fried="Fried food in the last 24h",
              # scre_food_fresh_coffee_tea0="No coffee or tea in the last 24h",
              # scre_food_fresh_coffee_tea="Coffee or tea in the last 24h",
              # scre_food_fresh_red_wine0="No red wine in the last 24h",
              # scre_food_fresh_red_wine="Red wine in the last 24h",
              
              ex1_household_size="Household size",
              ex1_hot_meals_package_weekly0="No use   ",
              ex1_hot_meals_package_weekly="Use of disposable packages",
              ex1_diet_veggie_vegan0="Meat/fish",
              ex1_diet_veggie_vegan="Vegetarian or vegan",
              
              ex1_milk_weekly0="No/rarely milk",
              ex1_milk_weekly="Milk consumption",
              ex1_yog_weekly0="No/rarely yogurt",
              ex1_yog_weekly="Yogurt consumption",
              ex1_cheese_weekly0="No/rarely cheese",
              ex1_cheese_weekly="Cheese consumption",
              ex1_egg_weekly0="No/rarely eggs",
              ex1_egg_weekly="Eggs consumption",
              ex1_fish_weekly0="No/rarely fish",
              ex1_fish_weekly="Fish consumption",
              ex1_fruit_weekly0="No/rarely fruits",
              ex1_fruit_weekly="Fruits consumption",
              ex1_poultry_weekly0="No/rarely poultry",
              ex1_poultry_weekly="Poultry consumption",
              ex1_meat_weekly0="No/rarely meat (excl. poultry)",
              ex1_meat_weekly="Meat (excl. poultry) consumption",
              ex1_pork_weekly0="No/rarely processed meat",
              ex1_pork_weekly="Processed meat consumption",
              ex1_tofu_weekly0="No/rarely tofu",
              ex1_tofu_weekly="Tofu consumption",
              ex1_starch_weekly0="No/rarely cereal products",
              ex1_starch_weekly="Cereal products consumption",
              ex1_cornflakes_weekly0="No/rarely breakfast cereal",
              ex1_cornflakes_weekly="Breakfast cereal consumption",
              ex1_whole_grain_weekly0="No/rarely whole grain cereals",
              ex1_whole_grain_weekly="Whole grain cereals consumption",
              ex1_patat_weekly0="No/rarely potatoes",
              ex1_patat_weekly="Potatoes consumption",
              ex1_lentil_weekly0="No/rarely pulses",
              ex1_lentil_weekly="Pulses consumption",
              ex1_vegetable_weekly0="No/rarely cooked vegetables",
              ex1_vegetable_weekly="Cooked vegetables consumption",
              ex1_salad_weekly0="No/rarely raw vegetables",
              ex1_salad_weekly="Raw vegetables consumption",
              ex1_walnut_weekly0="No/rarely nuts",
              ex1_walnut_weekly="Nuts consumption",
              ex1_sugar_weekly0="No/rarely sweets",
              ex1_sugar_weekly="Sweets consumption",
              ex1_chips_weekly0="No/rarely salty snacks",
              ex1_chips_weekly="Salty snacks consumption",
              
              cluster="Food frequency cluster",
              cluster2_dairy_focused="Cluster: dairy focused",
              cluster3_high_fiber="Cluster: high-fiber",
              cluster4_plant_based="Cluster: plant-based",
              cluster5_meat_centered="Cluster: meat-centered",
              ex1_veggie_vegan='Vegetarian or vegan ',
              ex1_organic_milk="Organic milk consumption",
              ex1_organic_yog="Organic yogurt consumption",
              ex1_organic_cheese="Organic cheese consumption",
              ex1_organic_egg="Organic eggs consumption",
              ex1_organic_fish="Organic fish consumption",
              ex1_organic_fruit="Organic fruits consumption",
              ex1_organic_poultry="Organic poultry consumption",
              ex1_organic_meat="Organic meat (excl. poultry) consumption",
              ex1_organic_pork="Organic processed meat consumption",
              ex1_organic_tofu="Organic tofu consumption",
              ex1_organic_starch="Organic cereal products consumption",
              ex1_organic_cornflakes="Organic breakfast cereal consumption",
              ex1_organic_whole_grain="Organic whole grain cereals consumption",
              ex1_organic_patat="Organic potatoes consumption",
              ex1_organic_lentil="Organic pulses consumption",
              ex1_organic_vegetable="Organic cooked vegetables consumption",
              ex1_organic_salad="Organic raw vegetables consumption",
              ex1_organic_walnut="Organic nuts consumption",
              ex1_organic_sugar="Organic sweets consumption",
              ex1_organic_chips="Organic salty snacks consumption",
              
              ex1_deo_spray_weekly0="No/rarely deodorant spray",
              ex1_deo_spray_weekly="Deodorant spray usage",
              ex1_deo_roll_weekly0="No/rarely deodorant roll",
              ex1_deo_roll_weekly="Deodorant roll usage",
              ex1_bodylotion_weekly0="No/rarely body lotion",
              ex1_bodylotion_weekly="Body lotion usage",
              ex1_handcream_weekly0="No/rarely hand cream",
              ex1_handcream_weekly="Hand cream usage",
              ex1_perfume_weekly0="No/rarely perfume",
              ex1_perfume_weekly="Perfume usage",
              ex1_hairspray_weekly0="No/rarely hairs pray",
              ex1_hairspray_weekly="Hair spray usage",
              ex1_toothpaste_weekly0="No/rarely toothpaste",
              ex1_toothpaste_weekly="Toothpaste usage",
              
              ex1_hot_meals_package_freq="Use of disposable packages ",
              ex1_milk_freq="Milk consumption ",
              ex1_yog_freq="Yogurt consumption ",
              ex1_cheese_freq="Cheese consumption ",
              ex1_egg_freq="Eggs consumption ",
              ex1_fish_freq="Fish consumption ",
              ex1_fruit_freq="Fruits consumption ",
              ex1_poultry_freq="Poultry consumption ",
              ex1_meat_freq="Meat (excl. poultry) consumption ",
              ex1_pork_freq="Processed meat consumption ",
              ex1_tofu_freq="Tofu consumption ",
              ex1_starch_freq="Cereal products consumption ",
              ex1_cornflakes_freq="Breakfast cereal consumption ",
              ex1_whole_grain_freq="Whole grain cereals consumption ",
              ex1_patat_freq="Potatoes consumption ",
              ex1_lentil_freq="Pulses consumption ",
              ex1_vegetable_freq="Cooked vegetables consumption ",
              ex1_salad_freq="Raw vegetables consumption ",
              ex1_walnut_freq="Nuts consumption ",
              ex1_sugar_freq="Sweets consumption ",
              ex1_chips_freq="Salty snacks consumption ",
              ex1_deo_spray_freq="Deodorant spray usage ",
              ex1_deo_roll_freq="Deodorant roll usage ",
              ex1_bodylotion_freq="Body lotion usage ",
              ex1_handcream_freq="Hand cream usage ",
              ex1_perfume_freq="Perfume usage ",
              ex1_hairspray_freq="Hair spray usage ",
              ex1_toothpaste_freq="Toothpaste usage ",
              
              ex1_tuna0="No/rarely tuna",
              ex1_tuna="Frequent tuna",
              ex1_salmon0="No/rarely salmon",
              ex1_salmon="Frequent salmon",
              ex1_pangasius0="No/rarely pangasius",
              ex1_pangasius="Frequent pangasius",
              ex1_tilapia0="No/rarely tilapia",
              ex1_tilapia="Frequent tilapia",
              ex1_trout0="No/rarely trout",
              ex1_trout="Frequent trout",
              ex1_shrimp0="No/rarely shrimp",
              ex1_shrimp="Frequent shrimp",
              ex1_fishfingers0="No/rarely fishfingers",
              ex1_fishfingers="Frequent fishfingers",
              
              ex1_residence_urban="Residence in urban/industrial area",
              ex1_tapwater="Tap water consumption",
              ex1_alcool="Alcool consumption ",
              ex1_alcool_weekly="Alcool consumption",
              
              ex2_skiwax0="No private exposition to ski wax",
              ex2_skiwax="Private exposition to ski wax",
              ex2_garden_pesticides0="No private exposition to pesticides",
              ex2_garden_pesticides="Private exposition to pesticides",
              ex2_spray_imp0="No private exposition to impregnation sprays",
              ex2_spray_imp="Private exposition to impregnation sprays",
              
              ex2_prof_smoke0="No professional exposition to smoke",
              ex2_prof_smoke="Professional exposition to smoke",
              ex2_prof_exhaust_gas0="No professional exposition to exhaust gas",
              ex2_prof_exhaust_gas="Professional exposition to exhaust gas",
              ex2_prof_solvent_vapours0="No professional exposition to solvent vapours",
              ex2_prof_solvent_vapours="Professional exposition to solvent vapours",
              ex2_prof_cleaning_agents0="No professional exposition to cleaning agents",
              ex2_prof_cleaning_agents="Professional exposition to cleaning agents",
              ex2_prof_dust0="No professional exposition to dust",
              ex2_prof_dust="Professional exposition to dust",
              ex2_prof_polycarbonate0="No professional exposition to polycarbonate",
              ex2_prof_polycarbonate="Professional exposition to polycarbonate",
              ex2_prof_epoxy_resin0="No professional exposition to epoxy resin",
              ex2_prof_epoxy_resin="Professional exposition to epoxy resin",
              ex2_prof_skiwax0="No professional exposition to ski wax",
              ex2_prof_skiwax="Professional exposition to ski wax",
              ex2_prof_spray_imp0="No professional exposition to impregnation sprays",
              ex2_prof_spray_imp="Professional exposition to impregnation sprays",
              
              hm_kids="Number of biological children",
              hm_breastfeeding0="No breastfeeding",
              hm_breastfeeding="Breastfeeding",
              hm_breastfeeding_months="Breastfeeding duration (in months)",
              ex1_carpet="Synthetic or natural carpet at home",
              ex1_carpet0="No synthetic or natural carpet at home",
              ex1_swiss_fish="Consumption of fish from swiss lakes",
              ex1_swiss_fishConsumptionoffishfromSwisslakes="Consumption of fish from swiss lakes ",
              ex1_swiss_fish0="No fish from swiss lakes",
              ex1_distance_field="Distance to nearest field/vineyard (in meters)",
              
              ant_height="Height",
              ant_weight="Weight",
              ant_waist_circ="Waist circumference",
              ant_bmi="BMI",
              
              ex1_cig="Consumption of smoked tobacco",
              ex1_cig_years="Duration of consumption (in years)",
              ex1_other_tobacco="Consumption of other tobacco products",
              ex1_other_tobacco_years="Duration of consumption (in years) ",
              
              ex1_residence_urbanResidenceinurbanDindustrialarea='Residence in urban/industrial area ',
              ex1_distance_fieldLessthan200mtonearestfieldDvineyard='Residence <200m from field/vineyard',
              ex2_garden_pesticidesExpositiontopesticides='Use of pesticide in the garden',
              ex2_skiwaxExpositiontoskiwax='Exposition to ski wax ',
              ex2_spray_impExpositiontoimpregnationsprays='Exposition to impregnation sprays ',
              ex1_tapwaterMorethan2Loftapwaterperday='Consumption of >2L of tap water per day',
              ex1_carpetSyntheticornaturalcarpet='Synthetic or natural carpet at home ',
              ex1_alcool_weeklyAtleastweekly='Alcohol at least weekly ',
              ex1_alcool_weeklyDailyandmore='Alcohol at least daily ',
              ex1_cigPastsmoker='Past user of smoked tobacco ',
              ex1_cigCurrentsmoker='Current user of smoked tobacco ',
              ex1_other_tobaccoPastuserofothertobaccoproducts='Past user of other tobacco products ',
              ex1_other_tobaccoCurrentuserofothertobaccoproducts='Current user of other tobacco products ',
              ex1_veggie_veganVegetarianDvegandiet='Vegetarian/vegan diet ',
              ex1_tunaFrequentconsumptionoftuna='Frequent consumption of tuna ',
              ex1_salmonFrequentconsumptionofsalmon='Frequent consumption of salmon ',
              ex1_pangasiusFrequentconsumptionofpangasius='Frequent consumption of pangasius ',
              ex1_troutFrequentconsumptionoftrout='Frequent consumption of trout ',
              ex1_shrimpFrequentconsumptionofshrimp='Frequent consumption of shrimp ',
              ex1_swiss_fishNoconsumptionoffishfromSwisslakes='Frequent consumption of fish from local lakes ',
              ex1_organic_fishGroup2='Organic fish group 2',
              ex1_organic_fishGroup3='Organic fish group 3',
              ex2_prof_smokeProfessionalexpositiontosmoke='Professional exposition to smoke ',
              ex2_prof_exhaust_gasProfessionalexpositiontoexhaustgas='Professional exposition to exhaust gas ',
              ex2_prof_solvent_vapoursProfessionalexpositiontosolventvapours='Professional exposition to solvent vapours ',
              ex2_prof_cleaning_agentsProfessionalexpositiontocleaningagents='Professional exposition to cleaning agents ',
              ex2_prof_dustProfessionalexpositiontodust='Professional exposition to dust ',
              ex2_prof_polycarbonateProfessionalexpositiontopolycarbonate='Professional exposition to polycarbonate ',
              ex2_prof_epoxy_resinProfessionalexpositiontoepoxyresin='Professional exposition to epoxy resin ',
              ex2_prof_skiwaxProfessionalexpositiontoskiwax='Professional exposition to ski wax ',
              ex2_prof_spray_impProfessionalexpositiontoimpregnationsprays='Professional exposition to impregnation sprays ',
              hm_breastfeedingBreastfeeding='Past breastfeeding '
  )
  # add to controls
  cc$pfas_list <- pfas_list
  cc$pfas_labels <- pfas_labels
  cc$labs <- labs
  return(cc)
}
